Feature/jc 519 vanilla js book catalog
saritasa-nest/camp-js-2023-irina-tumanova pull request #1
Opened 2023-07-06 07:02 UTC by irinatumanova

2023-07-06 07:13 UTC, dmitrymaslov13 commented
@irinatumanova please take a look at our code style by commits.
in this PR, you do not correspond to it

https://wiki.saritasa.rocks/general/git/

2023-07-06 07:25 UTC, dmitrymaslov13 commented on .github/workflows/second-stage-pr-approval-process.yml
> +          requiredApprovesAmount: 10
@pavelzadorin-saritasa is everything okay?)
I think 10 is a lot :D

2023-07-06 10:01 UTC, golovachev-yaroslav requested changes

2023-07-06 10:01 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/style/index.css
> +@import url("@js-camp/theme/src/index.css");
1. Normalize.css
2. variables
3. base
4. ...

2023-07-06 10:04 UTC, golovachev-yaroslav commented
![image](https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/assets/79349309/ed17a5a9-1750-4b23-9c8a-1fa76bdbe1e9)
Red/orange color is good for validation, shows an invalid field.

2023-07-06 10:12 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/index.html
> +			<select class="body">
body- class for text design (from figma)

2023-07-06 10:49 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/style/components.css
> +        2 * var(--small-space) +
What can be done about it? This is a count of the total height of the components with filters. Maybe split into variables?

2023-07-06 10:54 UTC, kristinaSvobodinaSaritasa commented
According to design on mobile screen should be 2 pictures in the row, please fix it 
<img width="577" alt="Screenshot 2023-07-06 at 17 46 56" src="https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/assets/82072005/cfa26911-90ba-43cf-9502-459ff7579219">

2023-07-06 10:54 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/index.html
> +			<select class="body">
> body- class for text design (from figma)

Figma should not decide for a developer how to call class. Class names should be clear for developers.

2023-07-06 10:55 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/style/components.css
> +@media (max-width: 1000px) {
There is a size of 786, however, with this width, filters in one line will be very small. This is fine?

2023-07-06 10:57 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/index.html
> +			<input type="text" placeholder="e.g.Refactoring" class="body"/>
body-class for text decoration (from figma). Should I name the classes differently?

2023-07-06 10:57 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/index.html
> +	<a class="body social-link link" href="#">Github</a>
body-class for text decoration (from figma). Should I name the classes differently?

2023-07-06 16:41 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/exercise1/index.html
> +			</div>
Please stick to BEM methodology. Use 2 `_` for elements and 1 `_` for modifiers. For example:
```ruby
<div class="book-card">
	<div class="book-card__cover">
		<img src="assets/covers/01.png" alt=" book cover">
	</div>
	<h4 class="book-card__title_small">Master the Skill of Debugging CSS</h4>
</div>
```

2023-07-06 16:41 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/exercise1/style/components.css
> +  border-radius: var(--medius-border-radius);
Avoid hardcoded size
https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size

2023-07-09 12:18 UTC, dmitrymaslov13 reviewed
On a note:

It is considered very good practice to leave a link to the issue and a little explanation about the changes that you have implemented as part of the pull request.

it saves reviewers time and makes life better)

2023-07-09 12:18 UTC, dmitrymaslov13 commented on apps/vanilla/src/pages/exercise1/style/variables.css
> +  --medius-border-radius: 24px;
```suggestion
  --medium-border-radius: 24px;
```

2023-07-10 05:23 UTC, irinatumanova commented on apps/vanilla/src/pages/exercise1/style/components.css
> +  border-radius: var(--medius-border-radius);
This is necessary to align images of different sizes. Without this, the pictures will be different in height.

2023-07-10 06:08 UTC, golovachev-yaroslav approved these changes

2023-07-10 06:08 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/exercise1/style/components.css
> +  background-color: #fff;
Please use a variable.

2023-07-10 06:34 UTC, LocTran-saritasa approved these changes

2023-07-10 06:43 UTC, dmitrymaslov13 approved these changes

2023-07-10 06:43 UTC, dmitrymaslov13 commented on apps/vanilla/src/pages/exercise1/style/components.css
> +}
```suggestion
.footer__info {
  display: flex;
  align-items: center;
  gap: var(--little-space);
}

.button-to-top {
  margin-left: auto;
  cursor: pointer;
  border: none;
}
```

2023-07-10 06:43 UTC, dmitrymaslov13 commented on apps/vanilla/src/pages/exercise1/style/components.css
> +header {
Semantically, we can have several different `header` tags on a page.

I propose to slightly improve and add the `.header` class to the `<header>` and style it.

We generally try to never style tags directly, except when we global reset "user agent" styles.
This is due to the fact that styles for tags are always applied globally, in this case this is not a problem, but as the project grows and isolated styles appear, this can become a problem and lead to unpleasant side effects

2023-07-10 07:05 UTC, golovachev-yaroslav approved these changes

2023-07-10 07:07 UTC, merged