JC-567 angular anime item management
saritasa-nest/camp-js-2023-irina-tumanova pull request #10
Opened 2023-08-08 05:12 UTC by irinatumanova

Task: JC-567

2023-08-08 07:04 UTC, golovachev-yaroslav approved these changes

2023-08-08 07:23 UTC, dmitrymaslov13 commented on libs/core/mappers/anime/anime-form-data.mapper.ts
> +			trailer_youtube_id: model.trailerYoutubeId !== null ? model.trailerYoutubeId : null,
```suggestion
			trailer_youtube_id: model.trailerYoutubeId,
```

2023-08-08 07:37 UTC, dmitrymaslov13 commented on apps/angular/src/app/app.component.html
>  			<mat-icon fontIcon="logout" />
let's use `<ng-container *ngIf="isAuth$ | async; else Login">...</ng-container>` here

2023-08-08 07:37 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<h3 class="typography-subtitle anime-subtitle" *ngIf="details.titleJapanese.length > 0; else EmptyJapaneseTitle">{{details.titleJapanese}}</h3>
You have the option not to create an empty template for each case with the same text
or you can create pipe

```suggestion
			<h1 class="typography-title anime-title">{{ details.titleEnglish.length > 0 ? details.titleEnglish : 'unknown' }}</h1>
```

2023-08-08 07:43 UTC, irinatumanova commented on apps/angular/src/app/app.component.html
>  			<mat-icon fontIcon="logout" />
I am displaying a `Login` instead of a logout button, why repeat myself?

2023-08-08 11:57 UTC, timofei-maximov-saritasa requested changes

2023-08-08 11:57 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-manage/anime-edit-page/anime-edit-page.component.html
> +<camp-anime-form [anime$]="anime$" type="edit" />
Passing observables in not a good practice. It might lead to bugs, like let's say you/other developer will replace `anime$` for a behavior subject and then use `.next()` somewhere below. It will change your data. Let's use `async` pipe here

2023-08-08 11:57 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.ts
> +	private mapPaginationStreamToItemsStreamWithShareReplay<T>(paginationStream$: Observable<Pagination<T>>): Observable<readonly T[]> {
Let's rename this method. The name is too big and hard to read

2023-08-08 11:57 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.ts
> +	private setFormValueFromInputAnime(anime: AnimeDetails): void {
Same here

2023-08-08 11:57 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/studio.service.ts
> +	}
It's not a good solution. What if you will have 100.000+ studios? Will you fetch them at once?
Let's find a better solution. You can paginate through this data. 

It can be an infinite scroll or just `Load More` button

2023-08-08 11:57 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime/anime-form-data.mapper.ts
> +	const ANIME_RATING_TO_FTO = {
```suggestion
	const ANIME_RATING_TO_DTO = {
```

2023-08-08 12:37 UTC, irinatumanova commented on apps/angular/src/core/services/studio.service.ts
> +	}
I have a problem - in editing I only know the id of the selected genres/studios. To display them as selected in the `mat-select`, you need all the selected elements to be displayed in the `mat-option`. Alternatively, I can take the data for the selected elements from the `Input() anime.genres/studios` and put it in the `select`. Then I can make pagination for genres/studios. Is this a normal solution?

2023-08-08 13:45 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/studio.service.ts
> +	}
You have the same model `Genre`/`Studio` in `AnimeDetails` you can populate select with data(I mean titles for displaying). Then you can fetch genres and studios and merge this data from what you get from `getStudios`/`getGenres` methods.

Basically, data in `anime.genres`/`anime.studios` will be initial data for your selects.

2023-08-09 08:11 UTC, andrey-gazzaev requested changes

2023-08-09 08:11 UTC, andrey-gazzaev commented on apps/angular/src/theme/variables.css
>  	--accent-color: hsl(336deg 78% 43% / 100%);
Why did you decide to use `hsl` rather than `hex` or `rgb`? Does this approach have any advantages?

2023-08-09 08:11 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/components/delete-modal/delete-modal.component.html
> +	<button mat-raised-button type="submit" color="primary" (click)="data.delete()">Delete</button>
Using the `submit` type outside your own `form` can be a serious problem if you use that component inside another component's `form`.

2023-08-09 10:24 UTC, irinatumanova commented on apps/angular/src/theme/variables.css
>  	--accent-color: hsl(336deg 78% 43% / 100%);
Used these colors on vanilla, is this color declaration inconvenient?

2023-08-09 10:40 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			}),
I transferred this logic to a service with requests, is it possible to control navigation in it?

2023-08-09 10:55 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +			}),
I think it would be justified in this case.

2023-08-09 10:56 UTC, andrey-gazzaev commented on apps/angular/src/theme/variables.css
>  	--accent-color: hsl(336deg 78% 43% / 100%);
No, I'm just curious as to why you chose this particular form of recording color values.

2023-08-10 06:02 UTC, andrey-gazzaev approved these changes

2023-08-10 06:02 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/select-with-create/select-with-create.component.ts
> +				this.items$.next([...items, ...newItems]);
Spread operation is convenient but expensive you can use `concat`

2023-08-10 07:36 UTC, timofei-maximov-saritasa approved these changes
![image](https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/assets/86595911/14a05bef-206c-4aa0-9e91-b4b35344fdaa)
Good job! 

There is a bug with pre-set values. They are not marked as selected.

2023-08-10 07:36 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.html
> +				[getItems]="getGenres" />
Usually, we prefer to not pass callbacks and to work with `@Output` to keep consistency

2023-08-10 07:42 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<h3 class="typography-subtitle anime-subtitle">{{details.titleJapanese.length > 0 ? details.titleJapanese : 'unknown'}}</h3>
The anime's second title (Japanese) is displayed as a subtitle for me (like on some anime sites)

2023-08-10 07:46 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.html
> +				[getItems]="getGenres" />
**Comment on the photo above**

Not sure if this is a bug. I did it in the likeness of the example from _Angular Material_, the elements already selected in the `chips` are not marked in the `autocomplete` (just when you click on the selected element, nothing will happen). However, I can modify the component if it raises questions.

2023-08-10 08:04 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.html
> +				[getItems]="getGenres" />
We can select **Adventure** second time and then we will get two **Adventure** chips.

You can fix only duplication bug

2023-08-10 08:05 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-manage/anime-form/anime-form.component.html
> +				[getItems]="getGenres" />
Oh, I thought I fixed this bug, thanks!

2023-08-10 09:35 UTC, dmitrymaslov13 approved these changes
It's very cool that you understood and implemented the field form material. Well done!

2023-08-10 09:35 UTC, dmitrymaslov13 commented on apps/angular/src/shared/components/base-mat-form-field/base-mat-form-field.component.ts
> +		}
At the moment we not get null, because you get form control from ngControl

2023-08-11 03:54 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-08-11 05:18 UTC, dbitkovski approved these changes

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<h3 class="typography-subtitle anime-subtitle">{{details.titleJapanese.length > 0 ? details.titleJapanese : 'unknown'}}</h3>
Not sure I know what Andrey meant but we try not to skip heading levels, like h1 is followed by h2. Probably he wanted to see `h1` - `h2` or `h2` - `h3` combination :)
I'm okay with `h1` for title because it's literally the main heading of the details page

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.html
> +			<button type="button" mat-raised-button color="primary" (click)="navigateToAnimeEditing()">Edit</button>
Why it's not a link? You can get anime id from `details` object

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +	private readonly id$: Observable<Anime['id']>;
Let's remove this property. Check my comments below with details.

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		return this.id$.pipe(
we can use `route.params` directly here

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		this.id$.pipe(
This one is not needed if we use `routerLink` from template

2023-08-11 05:18 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		this.id$.pipe(
use `details$` stream to get id from

2023-08-11 05:46 UTC, merged