JC 572 react authorization feature
saritasa-nest/camp-js-2023-irina-tumanova pull request #12
Opened 2023-08-11 13:22 UTC by irinatumanova

Task: JC-572

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/PasswordField/PasswordField.tsx
> +				id={props.name}
`htmlFor` should be the same as `id` in input.

You can use `useId` hook to sync these

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/RegistrationPage/RegistrationPage.tsx
> +					{...register('email', { required: true })}/>
You can omit `required` here since you are using `zod` to validate your form. 

https://zod.dev/?id=nonempty

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/RegistrationPage/RegistrationPage.tsx
> +					{...register('email', { required: true })}/>
We can improve ux by using 
`InputLabelProps={{ required: true }}` this will add asterisk to mark field as `required` this is purely UI thing.

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +			<form className={`${classes['auth-form']}`} onSubmit={handleSubmit(onSubmit)}>
```suggestion
			<form className={classes['auth-form']} onSubmit={handleSubmit(onSubmit)}>
```

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +					className={`${classes['auth-form__auth-change']}`}>
```suggestion
					className={classes['auth-form__auth-change']}>
```

2023-08-14 05:28 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +				<Button variant="contained" className={`${classes['auth-form__submit']}`} type="submit">Submit</Button>
```suggestion
				<Button variant="contained" className={classes['auth-form__submit']} type="submit">Submit</Button>
```

If you going to use multiple classes, then you can use `clsx` library

2023-08-14 05:57 UTC, golovachev-yaroslav requested changes

2023-08-14 05:57 UTC, golovachev-yaroslav commented on apps/react/src/api/interseptors/refreshTokenInterceptor.ts
> +		throw err;
It would be better `error`
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2023-08-14 05:57 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/RegistrationPage/RegistrationPage.tsx
> +					label="Email"
Is it really Email, looks like last name.

2023-08-15 17:22 UTC, irinatumanova commented on apps/react/src/routes/guards/AuthGuard.tsx
> +	const hasToken = UserSecretService.hasToken();
Is it better to use store?

2023-08-16 05:02 UTC, golovachev-yaroslav requested changes

2023-08-16 05:02 UTC, golovachev-yaroslav commented on apps/react/src/theme/variables.css
> +	--on-surface: hsl(0deg 0% 0% / 16%);
If a value equals 0 you don't need add %, px, rem, just 0 enough.

2023-08-16 06:00 UTC, timofei-maximov-saritasa commented on apps/react/src/api/services/userSecretService.ts
> +export namespace UserSecretService {
We have a naming convention for files in react project:
`PascalCase` for components
`camelCase` the rest

2023-08-17 04:04 UTC, golovachev-yaroslav commented on apps/react/src/routes/guards/AuthGuard.tsx
> +	const hasToken = UserSecretService.hasToken();
Discussed.

2023-08-17 05:09 UTC, golovachev-yaroslav approved these changes

2023-08-18 10:30 UTC, timofei-maximov-saritasa approved these changes

2023-08-18 11:00 UTC, andrey-gazzaev approved these changes

2023-08-18 11:00 UTC, andrey-gazzaev commented on libs/core/mappers/auth/verifiable-user-secret.mapper.ts
> +}
Do you use this mapper?

2023-08-20 09:41 UTC, viktor-sakhno-saritasa approved these changes

2023-08-21 09:37 UTC, pavelzadorin-saritasa requested changes

2023-08-22 08:57 UTC, golovachev-yaroslav approved these changes

2023-08-23 10:49 UTC, pavelzadorin-saritasa approved these changes

2023-08-23 11:03 UTC, merged