Feature/jc 577 filter infinity scroll
saritasa-nest/camp-js-2023-irina-tumanova pull request #13
Opened 2023-08-22 09:25 UTC by EgorRyazanov

2023-08-22 11:23 UTC, golovachev-yaroslav approved these changes

2023-08-22 11:23 UTC, golovachev-yaroslav commented on apps/react/src/components/MultipleFilter/MultipleFilter.tsx
> +import { InputLabel } from '@mui/material';
What if import `{ InputLabel, FormControl, MenuItem } from '@mui/material';` ?

2023-08-24 04:29 UTC, golovachev-yaroslav requested changes

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/LoginPage/LoginPage.tsx
> +		<div className={`${styles.auth}`}>
Maybe just `<div className={styles.auth}>`?

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/RegistrationPage/RegistrationPage.tsx
> +	const setValidationErrors = () => {
Looks like it repeats in Login page. I think it could be a function placed in src/utils.

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/pages/RegistrationPage/RegistrationPage.tsx
> +					label="First name"
It think you can avoid from type casting
`helperText={errors.firstName?.message ?? ''}`

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +			<InfinityScroll lastItemRef={lastItemRef} handleObserve={handleObserve}>
Usually props attribute with prefix `on` and handler functions `handle`
`<InfinityScroll lastItemRef={lastItemRef} onObserve={handleObserve}>`

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/hooks/useUserState.ts
> +	readonly user: User | null;
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-context-duplication
```
isLoading
error
```
much better

2023-08-24 04:29 UTC, golovachev-yaroslav commented on apps/react/src/store/auth/slice.ts
> +			.addCase(AuthDispatcher.reset, state => {
Maybe like in apps/react/src/store/genre/slice.ts ?
```
reducers: {
		reset(state) {
			state.isLoading = false;
			state.error = undefined;
		},
	},
```

2023-08-24 05:29 UTC, timofei-maximov-saritasa commented on apps/react/src/components/MultipleFilter/MultipleFilter.tsx
> +const MultipleFilterComponent = <T extends string, R extends FieldValues>({
It doesn't look like `MultipleFilter` for me. It is just `Select` wrapped with `react-hook-form`. Please, come up with a better name for the component.

2023-08-24 05:29 UTC, timofei-maximov-saritasa commented on apps/react/src/components/InfinityScrollCards/InfinityScrollCards.tsx
Please, rename file to match component name

2023-08-24 05:29 UTC, timofei-maximov-saritasa commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
> +		<Divider />
Usually, we don't put `Divider` inside components that will be rendered multiple times.

It is the same thing as putting `margin-bottom` inside a component.

2023-08-24 11:06 UTC, golovachev-yaroslav approved these changes

2023-08-25 07:40 UTC, maxineo commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +	/** Getting genre type array. */
I think thats obviuos, no need for such comments.

2023-08-25 07:45 UTC, maxineo commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +	const items = useMemo(() => GenreType.toArray(), [GenreType]);
`items` is a pretty generic name. Especially for a page component which can be very long. Lets give it a more strict name, `genreTypes` perhaps?

2023-08-25 07:54 UTC, maxineo commented on libs/core/mappers/genre/genre.mapper.ts
> +	const GENRE_TYPE_FROM_DTO: Record<GenreTypeDto, GenreType> = {
You can also add `Readonly` to the type.

2023-08-25 07:56 UTC, maxineo commented on libs/core/models/genre/genre-params.ts
> +export type QueryGenreParams = PaginationParams &
Lets document this type.

2023-08-25 07:57 UTC, maxineo commented on libs/core/models/genre/genre-params.ts
> +	types: string;
MIssing `readonly`.

2023-08-25 09:39 UTC, andrey-gazzaev approved these changes

2023-08-25 09:39 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreCard/GenreCard.tsx
> +));
A fragment in this case would be redundant
```suggestion
const GenreCardComponent = forwardRef<HTMLLIElement | null, Props>(({ genre }, forwardedRef) => (
		<ListItem ref={forwardedRef} alignItems="flex-start" className={styles.card}>
			<ListItemText
				primary={genre.name}
				secondary={
					<Typography sx={{ display: 'inline' }} component="span" variant="body2" color="text.primary">
						{GenreType.toReadable(genre.type)}
					</Typography>
				}
			/>
		</ListItem>
));
```

2023-08-25 09:39 UTC, andrey-gazzaev commented on libs/core/models/genre/genre-type.ts
> +	const TO_READABLE_TYPE: Record<GenreType, string> = {
```suggestion
	const GENRE_TYPE_TO_READABLE_MAP: Record<GenreType, string> = {
```

2023-08-25 11:53 UTC, EgorRyazanov commented on apps/react/src/components/InfinityScroll/InfinityScroll.tsx
> +	readonly onObserve: () => void;
In this case, i think, name of prop should be abstraction, because we could put to the component any logic we want

2023-08-25 12:26 UTC, merged