JC 581 react drawer and header
saritasa-nest/camp-js-2023-irina-tumanova pull request #14
Opened 2023-08-22 16:18 UTC by irinatumanova

Task: JC-581

2023-08-23 04:24 UTC, golovachev-yaroslav requested changes

2023-08-23 04:24 UTC, golovachev-yaroslav commented on apps/react/src/components/AppHeader/components/AppAuthHeader/AppAuthHeader.tsx
> +	const checkIsNotMainPage = (): boolean => location.pathname !== '/';
Maybe this instead of function?
`const isNotMainPage = location.pathname !== '/';`

2023-08-23 04:24 UTC, golovachev-yaroslav commented on apps/react/src/components/AppLayout/AppLayout.tsx
> +		<div id='app-shadow-loader-root'></div>
JXS/TSX not required closing tags in this case
`<div id='app-shadow-loader-root' />`

2023-08-23 06:04 UTC, timofei-maximov-saritasa approved these changes

2023-08-23 06:55 UTC, golovachev-yaroslav approved these changes

2023-08-25 10:19 UTC, golovachev-yaroslav approved these changes

2023-08-25 11:06 UTC, panov-aleksey-saritasa approved these changes

2023-08-25 11:35 UTC, merged