Feature/jc 577 menu and item details logic
saritasa-nest/camp-js-2023-irina-tumanova pull request #15
Opened 2023-08-25 12:51 UTC by EgorRyazanov

2023-08-25 13:25 UTC, golovachev-yaroslav requested changes

2023-08-25 13:25 UTC, golovachev-yaroslav commented on apps/react/src/components/AppLayout/AppLayout.tsx
> +		<div id="app-shadow-loader-root"></div>
PLease use self-closing tag here, 

` <div id="app-shadow-loader-root" />`

2023-08-25 13:25 UTC, golovachev-yaroslav commented on apps/react/src/features/studios/pages/StudiosPage/StudiosPage.tsx
> +	const drawerWidth = 400;
It could be outside the component.

2023-08-25 13:25 UTC, golovachev-yaroslav commented on apps/react/src/features/studios/pages/StudiosPage/StudiosPage.tsx
> +
`const DRAWER_WIDTH = 400;`

2023-08-25 13:25 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/routes.tsx
> +		element: <Navigate to="AnimePage" />,
`to="AnimePage"` is it real path?

2023-08-25 13:25 UTC, golovachev-yaroslav commented on apps/react/src/features/studios/components/StudioList/StudioList.tsx
> +					<Divider></Divider>
`<Divider />`, please check all empty tags.

2023-08-25 14:07 UTC, andrey-gazzaev requested changes

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/components/MultipleSort/MultipleSort.tsx
> +		}
`value[index].direction === 'asc' ? 'desc' : 'asc'`

Empty value can be disregarded as the value coming from the server is sorted.

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/features/anime/components/AnimeCard/AnimeCard.tsx
> +	<>
```suggestion

```

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	types: AnimeType[];
`readonly`

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const { register, handleSubmit, control } = form;
```suggestion
	const { register, handleSubmit, control } = useForm<FormValues>({
		defaultValues: defaultFormValues,
	});
```

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const typeItems = useMemo(() => Object.values(AnimeType).slice(0, -1), [AnimeType]) as AnimeType[];
Why don't you put this value behind the component?

2023-08-25 14:07 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const typeItems = useMemo(() => Object.values(AnimeType).slice(0, -1), [AnimeType]) as AnimeType[];
Also, why did you pass non-modifiable values to the hook that are not related to the component?

2023-08-28 03:52 UTC, golovachev-yaroslav commented on apps/react/src/components/AppLayout/AppLayout.tsx
> +		<div id='app-shadow-loader-root' />
For html prefer `"` instead of `'`

2023-08-28 03:53 UTC, golovachev-yaroslav approved these changes

2023-08-28 10:21 UTC, andrey-gazzaev approved these changes

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +const thisPageSortFields: Sorting<AnimeSortingField>[] = [
`this` in the context of the program has a different value it `default`.

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	readonly types: AnimeType[];
```suggestion
	readonly types: readonly AnimeType[];
```

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +					name={'sorting'}
```suggestion
					name="sorting"
```

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenreDetailsPage/GenreDetailsPage.tsx
> +	}, [id]);
The `id` may not be there when the component is loaded?

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenreDetailsPage/GenreDetailsPage.tsx
> +	if (errors) {
Avoid casting types.

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +						title={'Filter'}
```suggestion
						title="Filter"
```

2023-08-28 10:21 UTC, andrey-gazzaev commented on libs/core/models/anime/anime-sort.ts
> +	export function toArray(): readonly AnimeSortingField[] {
```suggestion
	export function toArray(): AnimeSortingField[] {
```

2023-08-28 10:21 UTC, andrey-gazzaev commented on libs/core/models/studio/studio.ts
> +	public readonly modified: Date;
Are you using these fields?

2023-08-28 10:21 UTC, andrey-gazzaev commented on apps/react/src/features/NotFoundPage/NotFoundPage.tsx
> +
```suggestion
```

2023-08-28 12:16 UTC, merged