Feature/jc 579 react anime list
saritasa-nest/camp-js-2023-irina-tumanova pull request #18
Opened 2023-08-28 07:27 UTC by Emil-Arzumanov

2023-08-28 12:49 UTC, pavel-romanov8 requested changes

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/components/AnimeCard/AnimeCard.tsx
> +	<ListItem ref={forwardedRef} alignItems="flex-start" className={styles.animeCard}>
Can we use CSS instead of material `sx` and most other props? The current implementation has 3 possible styling points:
1. CSS modules
2. Props like `alignItems`
3. MUI theme

It is really confusing to see `gap` usage in the CSS module without any additional display properties. I would use the first and third styling options as much as possible and avoid the second one

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/components/AnimeCard/AnimeCard.tsx
> +		<Avatar sx={{ width: 80, height: 80 }} src={anime.imageUrl}></Avatar>
Looks like it can be a self-closing tag

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.module.css
> +	top: 64px;
It would be great to have a dedicated CSS custom property so we can reuse it elsewhere

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	{ field: AnimeSortingField.TitleEnglish, direction: '' },
I understand it was designed before, but seeing direction as any empty string confuses me

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const [isOpenMenu, setIsOpenMenu] = useState(false);
```suggestion
	const [isMenuOpened, setIsMenuOpened] = useState(false);
```

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const [lastItemNode, setLastItemNode] = useState<HTMLLIElement | null>(null);
Do we really need to keep this node in a state? Usually `useRef` is a better option for HTML elements since we can directly tight it with an attribute

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +		dispatch(clearAnimeListState());
This logic looks like a problem with the management of the anime state overall. Can we thing of the other approach that doesn't assume a stale state on the component mount?

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +			pagination: { ...prevState.pagination, pageNumber: prevState.pagination.pageNumber + 1 },
Looks like you are using class for `pagination`, but here it is a simple object which might break our runtime

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +			pagination: { ...prevState.pagination, pageNumber: prevState.pagination.pageNumber + 1 },
I see this approach with parameters was already used before, but I would avoid directly having it in the component since it only brings a lot of noise. Instead, we can use `useReducer` for params and handle all related logic of updating parameters there. That way, our component doesn't hold all logic related to the parameters, looks cleaner, and we have a dedicated place for it

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +						name='sorting'
Do we have linter rules for single quotes of attributes? Usually we use double quotes for it

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +						{isLoading && animeList.length === 0 && <AppShadowLoader />}
Can we move the loader outside of the infinite scroll and avoid using fragments?

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const getNextPaginationData = () => {
Since you are passing this function as a prop we can wrap it into the `useCallback` just to be on a safe side

2023-08-28 12:49 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +									ref={index === animeList.length - 1 ? getLastAnimeNode : null}
Such flow with a somewhat dynamic ref can be improved. We can 2 anime cards conditionally instead of passing ref conditionally. That way, we don't need to have this attribute for most of the other cards, and `userRef` would be an appropriate solution

2023-08-28 15:52 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/AnimeCard/AnimeCard.module.css
> +	gap: 10px;
I seen you use variables for gaps in other file, please be consistent

2023-08-28 15:52 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +		<Box sx={{ flex: 1, display: 'flex' }}>
Please use styles to be consistent

2023-08-28 15:52 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
I think you can decompose a component into two. It will reduce complexity.

2023-08-30 04:43 UTC, SofyaKirillova commented on apps/react/src/components/MultipleSort/MultipleSort.module.css
> +	color: gray;
Let's use color in hex

2023-08-30 04:43 UTC, SofyaKirillova commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.module.css
> +	position: sticky;
`position: sticky;` does not affect the display of `aside`

2023-08-30 04:43 UTC, SofyaKirillova commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +				<InfinityScroll lastItemNode={lastItemNode} onObserve={getNextPaginationData}>
I suggest processing the case if no anime is found according to the parameters set by the user

2023-08-30 08:59 UTC, EgorRyazanov commented on apps/react/src/components/MultipleSort/MultipleSort.module.css
> +	color: gray;
It was resolved in another branch: feature/JC-579-sorting-fix

2023-08-30 09:34 UTC, EgorRyazanov commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const [lastItemNode, setLastItemNode] = useState<HTMLLIElement | null>(null);
Initially I used useRef, but there was a problem, sometimes it became null and all the functionality stopped working. Also, the ref does not notify about changes. I found a solution to this problem in the official react documentation: https://legacy.reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node

2023-08-30 09:43 UTC, EgorRyazanov commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.module.css
> +	position: sticky;
It does affect. When details appear on the right and the page increases in size by more than 100vh, the aside structure collapses

2023-08-30 10:13 UTC, EgorRyazanov commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +		dispatch(clearAnimeListState());
I came up with 2 options:
1) Delete the state when unmounting - I'm not sure if this is any different from the current implementation
2) Transfer the current state to async thunk every time, but this way we will do extra logic

2023-08-31 02:31 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +		dispatch(clearAnimeListState());
Where does this stale state come from?

2023-08-31 02:32 UTC, pavel-romanov8 commented on apps/react/src/features/anime/pages/AnimePage/AnimePage.tsx
> +	const [lastItemNode, setLastItemNode] = useState<HTMLLIElement | null>(null);
What is the case where you need to be notified about changes?

2023-09-01 03:55 UTC, closed without merging