Features/jc 538 angular anime app
saritasa-nest/camp-js-2023-irina-tumanova pull request #5
Opened 2023-07-18 08:31 UTC by irinatumanova

Task link: https://saritasa.atlassian.net/browse/JC-536

2023-07-18 09:20 UTC, dmitrymaslov13 requested changes

2023-07-18 09:20 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime.component.ts
> +export class AnimeComponent {}
Let's rename this component to `AnimePageComponent`

2023-07-18 09:20 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +          [pageIndex]="(page$ | async)!"
Please not use `!`, you can use `*ngIf` for this moment, or `??` operator

2023-07-18 09:20 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime.module.ts
> +
Please remove empty line

2023-07-18 09:20 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor(private http: HttpClient) { }
Please don't forget about readonly

```suggestion
	public constructor(private readonly http: HttpClient) { }
```

2023-07-18 09:20 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +				delay(500),
Why you add delay?

2023-07-18 09:20 UTC, dmitrymaslov13 commented on libs/core/dtos/anime.dto.ts
> +export enum AnimeTypeDto {
Usually we create simlar enum and use in it domain layer

```ts
/** Anime statuses. */
export enum AnimeStatus {
  Airing = 'AIRING',
  Finished = 'FINISHED',
  NotYetAired = 'NOT_YET_AIRED',
  Unknown = 'unknown',
}

export namespace AnimeStatus {

  const TO_READABLE_MAP: Readonly<Record<AnimeStatus, string>> = {
    [AnimeStatus.Airing]: 'Airing',
    [AnimeStatus.Finished]: 'Finished',
    [AnimeStatus.NotYetAired]: 'Not yet aired',
    [AnimeStatus.Unknown]: 'Unknown',
  };

  /**
   * Converts a certain anime status into readable equivalent.
   * @param value AnimeListItem type.
   */
  export function toReadable(value: AnimeStatus): string {
    return TO_READABLE_MAP[value];
  }

  /**
   * Converts string into anime status.
   * @param value Value.
   */
  export function toAnimeStatus(value: string): AnimeStatus {
    const type = value as AnimeStatus;
    return TO_READABLE_MAP[type] ? type : AnimeStatus.Unknown;
  }
}

export const ANIME_STATUS_READABLE_MAP = {
  [AnimeStatus.Airing]: AnimeStatus.toReadable(AnimeStatus.Airing),
  [AnimeStatus.Finished]: AnimeStatus.toReadable(AnimeStatus.Finished),
  [AnimeStatus.NotYetAired]: AnimeStatus.toReadable(AnimeStatus.NotYetAired),
  [AnimeStatus.Unknown]: AnimeStatus.toReadable(AnimeStatus.Unknown),
};
```

2023-07-18 09:20 UTC, dmitrymaslov13 commented on libs/core/models/pagination.dto.ts
Please rename file! It is not dto.

Also in domain model you can rename fields for more understandable.

For example `next: string` describes very badly what kind of line it is.
I believe it describes pagination for the next page, well if that's the case I would recommend using the limit and offset pagination model

2023-07-18 09:20 UTC, dmitrymaslov13 commented on libs/core/dtos/anime-query-params-dto.ts
> +export interface AnimeQueryParamsDto {
I think it is not queryParams, is params for get Anime (`GetAnimeParams` for example), but `limit` and `offset` is pagination params, and you can move pagination params into separate interface.

But cool that you described a separate interface for filters!

2023-07-18 11:23 UTC, LocTran-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.css
> +  max-height: 100%;
Avoid selecting the tag directly, we can give it a class and then select it.

2023-07-18 13:11 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper..ts
Typo in file name

`anime.mapper.ts`

2023-07-18 13:11 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +	public constructor(public readonly animeService: AnimeService) {
Service shouldn't be public

```suggestion
	public constructor(private readonly animeService: AnimeService) {
```

2023-07-18 13:11 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
Let's map this enum from dto.

This can be done with:

```ts
const ANIME_TYPE_FROM_DTO: Readonly<Record<AnimeTypeDto, AnimeType>> = {
  [AnimeTypeDto.Music]: AnimeType.Music,
  //  and so on...
}
```

2023-07-18 13:14 UTC, irinatumanova commented on libs/core/models/anime-status.ts
> +};
I agree, this was probably suggested in order not to call a function many times, but calling it would not be heavy

2023-07-18 13:17 UTC, irinatumanova commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
I've been told that `enums ` don't need to map since they are often used in the frontend and backend and are immutable.
@dmitrymaslov13

2023-07-19 07:10 UTC, irinatumanova commented on apps/angular/src/environments/environment.ts
> +	apiUrl: 'https://api.camp-js.saritasa.rocks/api/v1',
In this tutorial project, this is not required because this key is public.

2023-07-19 07:50 UTC, dmitrymaslov13 commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
Apparently, @timofei-maximov-saritasa  and I met different approaches on projects.

I personally prefer the option that @timofei-maximov-saritasa suggested.

but since this option is also used on projects, you can leave it as it is (unless of course someone asks for a change :D)

2023-07-19 07:57 UTC, irinatumanova commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
😢😢😢

2023-07-19 07:58 UTC, irinatumanova commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
I ended up leaving `enums` shared between the server and the front? Or do some of you think that this is very critical, you need to fix it? @timofei-maximov-saritasa @dmitrymaslov13

2023-07-19 08:13 UTC, gevorg-gevorgyan-saritasa commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
We use approach with `enums` mapping in a lots of projects. As @dmitrymaslov13 said, of course, you can leave it as it is, but I personally would recommend you to map this enum, since in the future there can be cases when mapping `enums` can be really useful.

2023-07-19 08:20 UTC, kristinaSvobodinaSaritasa approved these changes

2023-07-19 08:20 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table-page.component.ts
> +			tap(() => this.isLoading$.next(false)),
Please, implement error handling for the API request

2023-07-19 08:20 UTC, kristinaSvobodinaSaritasa commented on libs/core/mappers/list-params.mapper.ts
> +			ordering: `${model.sorting.direction === 'desc' ? '-' : ''}${model.sorting.field}`,
Please create  `enum SortDirection` to ensure type safety.

2023-07-19 11:20 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-table/anime-table-page.component.ts
> +		this.params$ = this.page$.pipe(
You not use `this.params$` in not constructor, please make it `const`

2023-07-19 11:39 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +	public getAllAnime(animeParams: AnimeParams): Observable<Pagination<Anime>> {
Is this method really returned all anime?

2023-07-19 13:08 UTC, irinatumanova commented on apps/angular/src/core/services/app-urls.config.ts
> +	}
This breaks my initial link https://api.camp-js.saritasa.rocks/api/v1, part of the link disappears. However, I can transfer part of this link in the arguments of the function, if it is better

2023-07-19 13:08 UTC, dmitrymaslov13 commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
I do not find this critical, since many projects also use the approach without mapping

2023-07-19 13:33 UTC, gevorg-gevorgyan-saritasa approved these changes

2023-07-19 13:33 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/theme/variables.css
> +  --surface-color: hsla(0deg 0% 26% / 100%);
Just curious, why not use `hex` here? 👽

2023-07-19 13:36 UTC, irinatumanova commented on apps/angular/src/theme/variables.css
> +  --surface-color: hsla(0deg 0% 26% / 100%);
In the last project, we used HSL

2023-07-19 13:47 UTC, pavelzadorin-saritasa commented on libs/core/dtos/anime.dto.ts
> +	readonly type: AnimeType;
From the point of view of abstraction, you need to do the mapping of enums in the same way as any other data types (which is logical), otherwise you will use the data of the storage layer at the level of the business model and display, and this is incorrect.

2023-07-20 10:38 UTC, pavel-romanov8 requested changes

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/components/not-found/not-found.component.css
> +.not-found__title {
Would be great to create a separate typography classes. That way we can avoid creation line-hight variables

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/components/not-found/not-found.component.html
> +    <p class="not-found__subtitle">Page not found :(</p>
Can we use heading tags instead of those `p`? Looks it would be more correct from semantic point of view

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/components/not-found/not-found.component.ts
> +	styleUrls: ['./not-found.component.css'],
Would be great to keep consistent styles for component declaration and use `changeDetection: ChangeDetection.OnPush`

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.css
> +  max-height: 100%;
Is it really necessary to specify `max-height` as well? Usually `max-width` works just fine

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +  <table mat-table [dataSource]="animeList.items" class="mat-elevation-z8" aria-describedby="anime list">
For material tables, we usually provide `trackBy` function that allows us to improve overall performance

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +      <th mat-header-cell *matHeaderCellDef> Image </th>
Is there a particular reason for keeping spaces around `Image`?

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +          <img [src] = "element.image" [alt]="element.titleEng + 'cover'" class="anime-page__image"/>
```suggestion
          <img [src]="element.image" [alt]="element.titleEng + 'cover'" class="anime-page__image" /> 
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +          *ngIf="{value: page$ | async} as page"
Looks like object construction is redundant

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	protected readonly isLoading$ = new BehaviorSubject<boolean>(false);
Generic is redundant where ts can infer type without a problem
```suggestion
	protected readonly isLoading$ = new BehaviorSubject(false);
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	protected readonly page$ = new BehaviorSubject<number>(defaultParams.page);
I would use `pageNumber` for this one

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		this.limit = event.pageSize;
Do we have to use `limit`? It looks like a BE related abstraction which leaked to our components. `pageSize` is pretty convenient and more understandable when it comes to work with tables

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +					filters: {
We can move these mapping into a separate function. It will allow us to keep stream pipe nice and clean as well as make the code more granular, which is always nice to have

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		this.limit = event.pageSize;
Can we merge page and page size into 1 subject values? Looks like there is no reason to keep them as separate fields

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/api-key.interceptor.ts
> +	public constructor(private readonly appConfig: AppConfig) {}
I saw you using `inject` for dependency injection in the component. Let's be consistent and do the same thing here

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/interceptors/api-key.interceptor.ts
> +/** Api key interceptor. */
```suggestion
/** API key interceptor. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +				catchError((error: unknown) => this.handleError(error as HttpErrorResponse)),
Please, be very careful with such errors handling. If expected type won't match, it might break your code

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/app-urls.config.ts
> +@Injectable({ providedIn: 'root' })
I saw that you provided this service to `AppModule`, but it is redundant if we make it as a root provider. I would leave the root provider and remove it from providers array in `AppModule`

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/app-urls.config.ts
> +		getAnime: this.toApi('anime/anime/'),
The usage of such route looks like `anime.getAnime` which is a bit awkward. The variant with `anime.get` looks more concise and readable

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/app.config.ts
> +@Injectable()
Can we inject it in root as you did with urls config service?

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/app.config.ts
> +	/** Api key for headers. */
```suggestion
	/** API key for headers. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +			fromObject: { ...ListParamsMapper.toDto(animeParams, AnimeFilterParamsMapper.toDto) },
`toDto` usually returns new object, so there is no need to create 1 more copy
```suggestion
			fromObject: ListParamsMapper.toDto(animeParams, AnimeFilterParamsMapper.toDto),
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/index.html
> +</head>
Looks like a problem with indentations

2023-07-20 10:38 UTC, pavel-romanov8 commented on apps/angular/src/shared/components/spinner/spinner.component.ts
> +	styleUrls: ['./spinner.component.css'],
Same thing with `changeDetection`

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime-filter-params.dto.ts
> +/** Filters params for getting anime dto. */
```suggestion
/** Filters params for getting anime DTO. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime-filter-params.dto.ts
> +	/** Selected anime types to display. */
I would try to avoid any relations to UI layer on our DTOs
```suggestion
	/** Anime types. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +/** Anime data dto. */
_data_ doesn't provide much meaning here
```suggestion
/** Anime DTO. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +	/** Anime id. */
```suggestion
	/** Anime ID. */
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +	readonly title_jpn: string;
Since they are placed in relative DTO we can omit reference to _anime_
```suggestion
	/** English title. */
	readonly title_eng: string;

	/** Japanese title. */
	readonly title_jpn: string;
```

2023-07-20 10:38 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +/** Anime statuses. */
```suggestion
/** Anime statuse. */
```

2023-07-20 11:03 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.css
> +  max-height: 100%;
This is necessary to maintain the aspect ratio of the image. If you remove max-height, then the image will stretch in height

2023-07-20 11:23 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		this.limit = event.pageSize;
How can I see the pageSize values for clearing the page number if that parameter, along with the page number, is in an Observable?

2023-07-21 04:46 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		this.limit = event.pageSize;
I am currently using `pageSize` in the `handlePageChange` method to reset the page when the `pageSize` changes. In order not to take the value from the `Observable`, I made `pageSize` a regular property

2023-07-21 05:02 UTC, timofei-maximov-saritasa approved these changes

2023-07-21 05:02 UTC, timofei-maximov-saritasa commented on nx.json
> +    "defaultCollection": "@nrwl/angular"
If I'm not mistaken, `@nrwl/*` is outdated. Use `@nx/angular` instead

2023-07-21 05:12 UTC, dbitkovski approved these changes

2023-07-21 05:12 UTC, dbitkovski commented on apps/angular/src/app/app.component.ts
>  	selector: 'camp-root',
I see in html and css files you use spaces for indentation. In ts files at the same time you use tabs. Make it consistent please

2023-07-21 05:12 UTC, dbitkovski commented on apps/angular/src/core/interceptors/http-error.interceptor.ts
> +					return throwError(() => new Error('Something bad happened; please try again later.'));
We don't need to create custom error here because we lose information about initial error. Just rethrow the error that comes as an argument.

2023-07-21 09:03 UTC, LocTran-saritasa approved these changes

2023-07-23 11:02 UTC, dmitrymaslov13 approved these changes

2023-07-23 11:02 UTC, dmitrymaslov13 commented on libs/core/models/anime.ts
> +		{ id, created, modified, titleEnglish, titleJapanese, imageUrl, aired, type, score, status, userScore }: InitAnimeParams,
Are you sure that in this case it is worth taking each field from the type, maybe something like this is better? anyway it's optional

```
public constructor(data: InitAnimeParams) {
  this.id = data.id;
  this.imageUrl = data.imageUrl;
  /// ... and more :D
}
```

2023-07-24 04:42 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			pageNumber: prev.pageSize === event.pageSize ? event.pageIndex : 0,
What do you mean by type casting?

2023-07-24 04:56 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			pageNumber: prev.pageSize === event.pageSize ? event.pageIndex : 0,
I'm sorry, the comment with the type casting is irrelevant

2023-07-24 05:11 UTC, dmitrymaslov13 commented on libs/core/mappers/list-params.mapper.ts
> +			ordering: `${model.sorting.direction === 'desc' ? SortDirectionDto.Desc : SortDirectionDto.Asc}${model.sorting.field}`,
I was talking about ordering mapping)))

2023-07-24 11:16 UTC, merged