Features/jc 544 angular anime list management
saritasa-nest/camp-js-2023-irina-tumanova pull request #6
Opened 2023-07-24 11:20 UTC by irinatumanova

2023-07-24 15:41 UTC, viktor-sakhno-saritasa approved these changes

2023-07-24 15:41 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +			class="mat-elevation-z8"
Do we need this class?

2023-07-24 15:41 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +				<td mat-cell *matCellDef="let element">{{(element.aired.start !== null) ? (element.aired.start | date) : "" }}</td>
I think it would be better, if we can avoid such hard to read expressions. I suggest to use something like that:

```suggestion
				<td mat-cell *matCellDef="let element">
				  <time 
				    *ngIf="element.aired.start as startDate; else emptyPlaceholder" 
				    [dateTime]="startDate
				  >
				    {{ startDate | date }}
				  </time>
				  
				  <ng-template #emptyPlaceholder>&mdash;</ng-template>
				</td>
```
Firstly, this approach allows you to make such logic clear to read. Also, you can move out `emptyPlaceholder` template to end of file and use it whenever, and it is good, because I believe it is good UX, when user clear see: there is `-` (no value) instead only empty space. Besides, in my example, we are keeping HTML semantic when we're using `time` for date properties.

2023-07-24 15:41 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				pageSize: +(params['pageSize'] ?? defaultParams.pagination.pageSize),
Maybe it's debatable, but I believe it would be better to use explicit type casting. Because, I think, we can face with such cases, when this record will be hard to read and when code contains a lot of symbols it can confuse.
```suggestion
				pageSize: Number(params['pageSize'] ?? defaultParams.pagination.pageSize),
```

2023-07-24 15:43 UTC, viktor-sakhno-saritasa commented
> Task link: https://saritasa.atlassian.net/browse/JC-544

BTW, when autolinks added to your project, you don't need to paste link to the task directly. You can write so: Task: JC-544 (I didn't add this link manually).

2023-07-25 01:58 UTC, dbitkovski requested changes

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +			<input matInput placeholder="e.g. Naruto" [formControl]="filtersForm.controls.search">
Use `formControlName` property of `matInput`. You'll be able to specify only the name of a control that's in the `filtersForm` group

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +			search: this.formBuilder.control(filters.search),
You can write it like this: `search: filters.search`. `FormBuilder` automatically transform it to control with the type infered from passed value

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				debounceTime(REQUEST_DEBOUNCE_TIME),
Why do we need debounce here? A time-based solution is considered a bad practice. If we can't find anything else, let's provide a comment at least :)

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				tap(() => this.isLoading$.next(false)),
If `this.animeService.getAnime(params)` stream throws an error, a callback function in the `tap` operator won't be called and you'll have infinite loading.

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				pageSize: +(params['pageSize'] ?? defaultParams.pagination.pageSize),
I would even say that if we know we work with integers, we can use `Number.parseInt()` method

2023-07-25 01:58 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +		window.scroll({ top: 0, left: 0, behavior: 'smooth' });
I don't know if you already listened to the lecture about dependency injection so if you didn't just ignore my comment.
Working with angular we prefer not to interact with global variables (such as `window` or `document`) and there are a few why's:
- if we decide to add tests, you need to mock `window` object and it's much easier to mock an object that's passed as parameter.
- right now our application runs only in the browser but we can't guarantee there won't be server-side rendering feature. When you add SSR to your project, the application is ran on the server and obvisously there is not `window` object there :)
- and the last point, working with direct dependencies is much easier because usually they're listed in one place (like constructor)
So if you decide to apply my suggesstion I want you to create an injection token and retrieve `window` object via it. You can use the same type `Window` but you can't interact with global object in your component.
If you have any questions, text me on slack

2023-07-25 01:58 UTC, dbitkovski commented on package.json
> +    "@ngneat/until-destroy": "^10.0.0-beta.0",
From the v16 angular has built-in solution for this https://netbasal.com/getting-to-know-the-destroyref-provider-in-angular-9791aa096d77

2023-07-25 03:37 UTC, khoanguyen-saritasa approved these changes

2023-07-25 03:37 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	protected readonly sorting$: BehaviorSubject<Sorting<AnimeSortingField>>;
Wrong docs description.

2023-07-25 03:37 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				tap(() => this.isLoading$.next(false)),
`finalize` will be a better operator in such case.

2023-07-25 03:37 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	private mapQueryParamsToAnimeParams(params: Params): AnimeParams {
You can create a generic type for params instead of using built-in Angular `Params` type to enhance type suggestions. Something like this will work perfectly fine: 
`export type QueryParamsOf<T extends Record<string, any>> = { [key in keyof Partial<T>]: string | undefined }; `

2023-07-25 04:59 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +			class="mat-elevation-z8"
This class adds shadows to the `table`, I think it looks better with them

2023-07-25 05:08 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.html
> +			<input matInput placeholder="e.g. Naruto" [formControl]="filtersForm.controls.search">
I had a conversation with @dmitrymaslov13 about this topic. formControlName will not show an error if I enter the wrong name, and formControl will immediately indicate an error in the code

2023-07-25 05:17 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				debounceTime(REQUEST_DEBOUNCE_TIME),
If there is no `debounce`, requests will be sent too often. What is the best way to replace such a delay?

2023-07-25 05:24 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				tap(() => this.isLoading$.next(false)),
`finalize` will be executed only after the subscription ends. Is it possible to leave `tap` and add `finalize`?

2023-07-25 05:39 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				tap(() => this.isLoading$.next(false)),
@irinatumanova Yes, you can omit `tap` operator at the end of your stream and add `finalize` to the `this.animeService.getAnime` stream like this: 
```
return combineLatest([
			this.filtersForm.valueChanges.pipe(startWith(this.filtersForm.value)),
			this.pagination$,
			this.sorting$,
		])
			.pipe(
				debounceTime(REQUEST_DEBOUNCE_TIME),
				map(([{ search, type }, pagination, sorting]) => this.createAnimeParams(pagination, sorting, search, type)),
				tap(params => this.setQueryParamsFromAnimeParams(params)),
				tap(() => this.isLoading$.next(true)),
				switchMap(params => this.animeService.getAnime(params).pipe(
					finalize(() => this.isLoading$.next(false)),
				)),
			);
```
Indeed, the subscription to the outside stream will not end until the component is destroyed, but the subscription of the `this.animeService.getAnime(params)` will end after the HTTP fetch is successful or failed. This is the most suitable place to put `finallize` operator in your case.

2023-07-25 06:19 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				debounceTime(REQUEST_DEBOUNCE_TIME),
It's fine in this case. My point was that you provide comment in code :)

2023-07-25 06:20 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				debounceTime(REQUEST_DEBOUNCE_TIME),
Oh sorry I misunderstood you :(

2023-07-25 06:26 UTC, dbitkovski requested changes

2023-07-25 06:26 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	@Inject(DOCUMENT) private window = inject(DOCUMENT).defaultView;
should be `readonly` as other props that are not reassigned over time

2023-07-25 06:26 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +					defaultParams.pagination.pageNumber,
Looks like generic solution. In this case it's better to create a function not to duplicate code in the future

2023-07-25 06:28 UTC, dbitkovski commented
@irinatumanova "Fix after review" is not a good commit message. It would be better if you have a bunch of commits but each has meaningful and understandable commit message 🐱

2023-07-25 11:47 UTC, dbitkovski approved these changes

2023-07-25 11:47 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				pageNumber: this.mapQueryParamToNumberParam(defaultParams.pagination.pageNumber, params.pageNumber),
Can we write a function that will create `PaginationParams` object? I think for every page that has pagination in URL query params we need to use the same interface so we can have a mapper function

2023-07-25 12:57 UTC, irinatumanova commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +				pageNumber: this.mapQueryParamToNumberParam(defaultParams.pagination.pageNumber, params.pageNumber),
Where is the best place to put this function? Is it a utility?

2023-07-26 11:14 UTC, merged