Features/jc 551 angular authorization
saritasa-nest/camp-js-2023-irina-tumanova pull request #7
Opened 2023-07-26 12:03 UTC by irinatumanova

2023-07-26 18:02 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/guards/auth.guard.ts
> +	return authService.isAuth$.pipe(
I recommend adding `first()` or `take(1)` operator there. Because, if I don't mistake, in your case, your guard will continue working while application will not be closed. So, if user will move between your routes a lot of times, it can bring performance issues. Guard and so runs every time when the user navigates through the application.

2023-07-26 18:19 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/error.service.ts
> +	public showErrorsToForm(errors: HttpError[], form: FormGroup): void {
It is nice that you did error handling for forms. But, obvious issue there - you broke layer abstraction. Form - it is something related to UI, `HttpError` it is closer to API layer, so, above I see you use `HttpError` in your components. 

When you face with such words like `Http`, `Request`, `Response` etc., it can indicate about broken layer abstraction. So, if one day, you will note, that backend updated their errors managements, you must make changes in UI components. 

One of the possible solutions: divide this functional and create two util functions: first function will transform `HttpError` data to error data related to some model, second - will catch errors inside your components and set errors for you passed form.

I think you can do it when you will have a free time. If you face with troubles, you can text me, and we together will think about that.

2023-07-26 18:32 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/error.service.ts
> +				form.controls[error.attr].setErrors({ ...form.controls[error.attr].errors, [error.code]: error.detail });
As I understand, your code won't work if `attr` from backend will be different from your from control name. And as additional to my text above, if you will separate this logic and your first util function will map error attrs to models you will fix it.

2023-07-26 18:33 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/storage.service.ts
> +	public async set<T>(key: string, value: T): Promise<void> {
Do we need to transform it to `Observable` to be consistent and don't mix `Promise` with `Observable`?

2023-07-27 04:46 UTC, khoanguyen-saritasa approved these changes

2023-07-27 04:46 UTC, khoanguyen-saritasa commented on libs/core/models/auth/registration.ts
> +	repeatedPassword: string;
```suggestion
	readonly repeatedPassword: string;
```

2023-07-28 03:10 UTC, dbitkovski requested changes

2023-07-28 03:10 UTC, dbitkovski commented on apps/angular/src/core/utils/validators.ts
> +				if (repeatedPassword.value.length < MIN_PASSWORD_LENGTH) {
I don't think this validator should check the length of the password. This is not it's responsibility.

2023-07-28 03:10 UTC, dbitkovski commented on apps/angular/src/shared/pipes/sentensecase.ts
> +		return `${value[0].toUpperCase()}${value.slice(1).toLowerCase()}`;
It throws an error if `value` is null or an empty string

2023-07-28 04:51 UTC, irinatumanova commented on apps/angular/src/app/features/auth/login-page/login-page.component.ts
> +			this.authService.login(this.form.getRawValue()).pipe(
Because I was advised in the comments above to use this function to avoid `Partial`

2023-07-28 04:54 UTC, irinatumanova commented on apps/angular/src/core/utils/validators.ts
> +				if (repeatedPassword.value.length < MIN_PASSWORD_LENGTH) {
Then it is better to check the error about the length in the errors? I need to throw a mismatch error when the password has at least the minimum length

2023-07-28 05:36 UTC, irinatumanova commented on apps/angular/src/core/services/auth.service.ts
> +		);
I tried to do it through concat, but when subscribing to `isAuth`, a lot of updates still took off. I ended up removing `userSecret` from `isAuth`, updating the value of `isAuthUpdated` once. As a result, `isAuth` when subscribing at the beginning returns only two values: initial `false`, and `true` if there are tokens

2023-07-28 05:45 UTC, irinatumanova commented on apps/angular/src/core/services/auth.service.ts
> +		);
```
this.isAuth$ = concat(
			this.userSecretService.getTokens().pipe(
				first(),
				map(tokens => tokens !== null),
				tap(isAuth => this.isAuthUpdated$.next(isAuth)),
			),
			this.isAuthUpdated$,
		);
```

Something like this always causes 2 calls, the option I made calls 1 update if the user is not logged in

2023-07-28 05:48 UTC, irinatumanova commented on apps/angular/src/app/features/auth/login-page/login-page.component.ts
> +			this.authService.login(this.form.getRawValue()).pipe(
https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/pull/7#discussion_r1275298528

2023-07-28 05:50 UTC, irinatumanova commented on apps/angular/src/core/utils/validators.ts
> +				if (repeatedPassword.value.length < MIN_PASSWORD_LENGTH) {
I decided to add a mismatch error only when the required password length is reached, because when the repeated password is not long enough, it will obviously not match the first password. Also, an error about insufficient length is a higher priority.

2023-07-28 06:08 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +		);
> Something like this always causes 2 calls
That makes sense. `getTokens()` emits the first value, then completes, `concat` subscribes to the `isAuthUpdated$` stream and since it's a `BehaviourSubject` it emits a value immediately.
Okay, I think it's not a problem if we'll go with your solution. Otherwise, you can make `isAuthUpdated$` a `Subject` and it should work fine.
Also, I'd recommend using `distinctUntilChanged()` operator to make sure the same value won't be emitted in a sequence.

2023-07-28 06:16 UTC, dbitkovski commented on apps/angular/src/core/utils/validators.ts
> +				if (repeatedPassword.value.length < MIN_PASSWORD_LENGTH) {
From the point of business logic it's not correct. There is a straightforward task: we need to check if passwords are the same. If you don't want to show "Password are different" error while the repeated password length is less than `MIN_PASSWORD_LENGTH` you should handle it on UI directly. 
Also, as you said `minLength` error has higher priority so it should as you want it without any changes. If `repeatedPassword.length < MIN_PASSWORD_LENGTH`, the control has 2 errors: insufficientLength and differentPassword. But since min length has higher priority we'll show only this error.

2023-07-31 01:50 UTC, dbitkovski requested changes

2023-07-31 01:50 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
>  	}
I'm not requesting changes, just in case you don't know about this feature:
```suggestion
	private createAnimeParams(
                pagination: PaginationParams,
                sorting: Sorting<AnimeSortingField>,
		search: string = defaultParams.filters.search,
                types: AnimeType[] = defaultParams.filters.types,
         ): AnimeParams {
		return {
			pagination,
			sorting,
			filters: { search, types },
		};
	}
```
Typescript allows us to set default values for parameters if arguments are not passed. We can use this feature to avoid extra checks in code.

2023-07-31 01:50 UTC, dbitkovski commented on apps/angular/src/app/features/auth/components/password-field/password-field.component.ts
> +export class PasswordFieldComponent implements OnInit {
Extra task 🥳 (if you don't feel like doing it, that's fine)
Although your solution is totally fine we can make it even better. Read about `ControlValueAccessor`. This feature allows you to create a component that will work with `ngModel` or `formControl` directives. Pretty powerful thing that we usually use for our custom controls.
If you have any questions, write to me on slack 📲

2023-07-31 01:50 UTC, dbitkovski commented on apps/angular/src/app/features/auth/components/password-field/password-field.component.ts
> +	protected shouldPasswordBeHidden = true;
`isPasswordHidden` would be a better option. You even prefered such a comment :)

2023-07-31 01:50 UTC, dbitkovski commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +				catchHttpErrorResponse(),
Looks like leak of abstractions. As you know components shouldn't know from where the data come. It simply asks a service-class to provide data, that's it.
I think it's better to use this operator in `AuthService.register` method

2023-07-31 01:50 UTC, dbitkovski commented on apps/angular/src/core/utils/validators.ts
> +				const { password, repeatedPassword } = group.controls;
That's really bad that your validator requires specific control names, it's not flexible and might lead to runtime errors.
I see that you apply this validator to `FormGroup` object which is not bad but make it more difficult to work with. I would recommend that you have the following workflow:
1) You apply this validator to a control that contains information about repeated password
2) `passwordRepetition` function requires control's name that contains original password

So in your case it will look similar to:
```
const form = formBuilder.group({
  password: [...],
  repeatedPassword: ['', [AppValidators.passwordRepetition('password')]]
})
```

2023-07-31 01:50 UTC, dbitkovski commented on libs/core/models/app-error.ts
> +export class AppError {
If you create a custom error, it's better to extend `Error` class. Otherwise you might see unexpected behaviour when you `throw new AppError()`

2023-07-31 03:05 UTC, viktor-sakhno-saritasa approved these changes

2023-07-31 05:35 UTC, irinatumanova commented on apps/angular/src/core/utils/validators.ts
> +				const { password, repeatedPassword } = group.controls;
I agree with this edit, but if I put the validator on control, then I have to pass not only the name, but also a link to the form in order to get the initial password data (is this normal?). Also, if I hang the validator on the control, the error will not disappear until I change the repeated password to the original one, however, when changing the original password to a repeated password one, nothing will happen.

2023-07-31 05:40 UTC, irinatumanova commented on libs/core/models/app-error.ts
> +export class AppError {
`AppError` should depend on `Error`? This is not an error object that comes from the server, but its nested field:
```
Error {
   error: {
      errors: {code, detail, attr}[]
   }
}
```
From the error object, I parse into my error object

```
AppErrors {
   [key: string]: AppError[]
}
```

2023-08-01 01:29 UTC, dbitkovski commented on apps/angular/src/core/utils/validators.ts
> +	export function passwordRepetition(originalPasswordName: string, repeatedPasswordName: string): ValidatorFn {
`originalPasswordName` - it's not a password name but name of a control

2023-08-01 04:22 UTC, merged