JC-557 angular details for anime
saritasa-nest/camp-js-2023-irina-tumanova pull request #8
Opened 2023-08-01 04:22 UTC by irinatumanova

Task: JC-557

2023-08-01 07:10 UTC, khoanguyen-saritasa requested changes

2023-08-01 07:10 UTC, khoanguyen-saritasa commented on libs/core/models/app-error.ts
>  }
Great work on building the `AppError` utility! However, there is room for further improvement. Currently, you are using `[key: string]: readonly AppErrorItem[];` as the error types, which can lead to loose type checking for different error types of endpoints. To enhance the type safety and make the `AppError` utility more robust, consider making it generic.

By making `AppError` generic, you can enforce stricter typing and ensure that errors are correctly associated with their respective endpoints. This improvement will result in more reliable type guards and help prevent potential errors in the future.

Of course, this is not mandatory. :) However, if you have the time and are interested in further research, you may want to consider potential improvements for this utility.

2023-08-01 07:12 UTC, khoanguyen-saritasa commented
And one more thing, I cannot open the detail page in the preview version. Seem like there is some errors occurred. Can you please check?
![image](https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/assets/108647361/5e442103-fc03-4d78-b13a-de4e6c950cfa)

2023-08-01 09:12 UTC, irinatumanova commented on libs/core/models/app-error.ts
>  }
I hope I understood you correctly [effe748](https://github.com/saritasa-nest/camp-js-2023-irina-tumanova/pull/8/commits/effe748555c078d1ef82c9b26b23c7467506abb8) :)

2023-08-07 03:37 UTC, viktor-sakhno-saritasa approved these changes

2023-08-07 03:37 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +				return this.refreshSecretRequest$.pipe(
Such logic isn't clear for me. Why we can't call `this.userSecretService.getTokens().pipe(...` directly? Why do we have `refreshSecretRequest$` variable? Can we avoid this one?

2023-08-07 03:37 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/user-secret.service.ts
> +			.subscribe();
Don't forget to unsubscribe.

2023-08-07 03:37 UTC, viktor-sakhno-saritasa commented on libs/core/mappers/anime/anime-details.mapper.ts
> +				`https://www.youtube.com/embed/${dto.trailer_youtube_id}` :
Let's move `youtube` src to our environment config.

2023-08-07 06:07 UTC, irinatumanova commented on apps/angular/src/core/interceptors/refresh-token.interceptor.ts
> +				return this.refreshSecretRequest$.pipe(
If the request to refresh the token occurs several times in a row, then I will not request a new token each time. For this, there is still shareReplay

2023-08-07 06:21 UTC, irinatumanova commented on libs/core/models/app-error.ts
>  }
I changed the work with errors, so this edit may not be relevant

2023-08-07 13:18 UTC, dmitrymaslov13 commented on apps/angular/src/core/services/anime.service.ts
> +			.pipe(map(detailsDto => AnimeDetailsMapper.fromDto(detailsDto, YOUTUBE_EMBED_URL)));
You can remove second arg from `fromDto` method and use global const `YOUTUBE_EMBED_URL` in method

2023-08-07 14:55 UTC, viktor-sakhno-saritasa commented on apps/angular/src/environments/environment.ts
> +	youtubeSrc: 'https://www.youtube.com/embed/',
I recommend moving external recourses to the environment file in any case. It does not matter, it will be changed or not in other configuration. Firstly, it allows us decrease using external resources directly in our app. Secondly, I think you can't be sure, that url or service will not be changed. And thirdly, I believe, it is useful, when we write tests. It easier to add test configuration instead replace constant inside testing service.

2023-08-08 03:12 UTC, khoanguyen-saritasa approved these changes

2023-08-08 04:56 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		this.details$ = this.animeService.getAnimeDetails(animeId).pipe(shareReplay({ refCount: true, bufferSize: 1 }));
Let's move create streams to separate methods

2023-08-08 04:56 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		const animeId = Number(this.route.snapshot.params['id']);
You can use `params` stream in this case.  this is a small change, but we will have the advantage that if the parameter changes, reactivity will do everything for us.

2023-08-08 04:58 UTC, dmitrymaslov13 approved these changes

2023-08-08 06:50 UTC, dbitkovski requested changes

2023-08-08 06:50 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		const animeId$ = this.route.params;
that's not `animeId$`, this stream contains query params

2023-08-08 06:50 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		fromEvent(this.window ?? window, 'resize')
`this.window ?? window` this is a bad fallback. Usually, if `document.defaultView` is undefined it means there is no `window` as well. Just remove this check and go with `this.window`

2023-08-08 06:50 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +		this.trailerComponentHeight$.next(this.window.innerWidth * TRAILER_COMPONENT_ASPECT_RATION);
Just a comment, no need to change this.
This is awesome that you make it fully responsible but usually that's not require to change size on resize. You can add thresholds so there are only 2-3 available sizes.

2023-08-08 06:50 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-details-page/anime-details-page.component.ts
> +	protected getReadableStatus(status: AnimeStatus): string {
I see you have the same function at anime-page. Let's create a pipe that we can use from template?

2023-08-09 03:55 UTC, pavelzadorin-saritasa approved these changes

2023-08-10 09:15 UTC, dbitkovski approved these changes

2023-08-10 09:15 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime-page/anime-page.component.ts
> +	protected trackById(index: number, anime: Anime): Anime['id'] {
Rename to `trackAnime`. Since this method works with `Anime` entity only it's better to specify it in name as well

2023-08-10 09:15 UTC, dbitkovski commented on apps/angular/src/shared/shared.module.ts
> +		YesNoPipe,
When you have a lot of declarations that should be exported from the module, you can create an array that includes them. And then use this array in `declarations` and `exports` sections.

2023-08-10 09:15 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/image-modal/image-modal.component.html
> +  <img [src]="data.imageUrl" [alt]="data.title + ' cover'">
Not a big deal but I see that html files are formatted with spaces, not tabs

2023-08-10 10:13 UTC, merged