JC-551 angular fix authorization
saritasa-nest/camp-js-2023-irina-tumanova pull request #9
Opened 2023-08-01 08:42 UTC by irinatumanova

Task: JC-551

2023-08-04 07:12 UTC, AndreySkripachev approved these changes

2023-08-04 07:12 UTC, AndreySkripachev commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +			.subscribe();
Subscribing to Observable changes without the ability to unsubscribe creates the possibility of memory leaks.

I found an [article](https://levelup.gitconnected.com/preventing-angular-subscription-memory-leaks-65f18eb9cb8e) that talks a bit about subscription management. You might find something there for your project

2023-08-04 07:12 UTC, AndreySkripachev commented on apps/angular/src/core/rxjs/catch-form-errors.ts
> +(source$: Observable<unknown>) => Observable<unknown> {
I think you can use the [OperatorFunction](https://rxjs.dev/api/index/interface/OperatorFunction) type here

2023-08-04 07:14 UTC, dmitrymaslov13 commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +				tap(() => this.router.navigate([''])),
in this implementation, we have a UI problem related to the fact that from whatever url we go to the page, if we are not authorized, we will get to the home page.

I think you can improve it)

2023-08-04 07:20 UTC, irinatumanova commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +			.subscribe();
I thought that the `first` you added, the unsubscribe would happen automatically after completion. Is it better to use the `untilDestroyed` operator?

2023-08-04 10:20 UTC, dbitkovski requested changes

2023-08-04 10:20 UTC, dbitkovski commented on libs/core/models/app-error.ts
> +		this.name = name;
As far as I understand the `name` property shouldn't be in public API of your class. [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#instance_properties) says that this property is set by a subclass only.

2023-08-04 10:20 UTC, dbitkovski commented on libs/core/models/app-error.ts
> +export class AppError<T extends Error> extends Error {
Do I understand correctly that `AppError` contains a dict of errors? I believe we should rename it because it became really complex and the name has nothing in common with functionality

2023-08-04 10:20 UTC, dbitkovski commented on libs/core/mappers/app-errors.mapper.ts
> +				const appErrorItem: Error = { name: httpError.code, message: httpError.detail };
You have to use a constructor function to get error object

2023-08-04 10:35 UTC, irinatumanova commented on libs/core/models/app-error.ts
> +		this.name = name;
Do not understand a little bit. If I have a class that extends on the `Error` class, can I pass both the `name` and the `message` to the constructor? Or should I do something like this:
```
const error = new MyError('my message')
error.name = 'my name'
```

2023-08-04 11:42 UTC, irinatumanova commented on libs/core/models/app-error.ts
> +		this.name = name;
I tried to change `AppError` to `AppErrorDictionary` with `errors: Recore<string, string[]>`

2023-08-07 03:41 UTC, viktor-sakhno-saritasa approved these changes

2023-08-07 03:41 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/login-page/login-page.component.ts
> +	}
I suggest making a separate service to work with query params. What do you think? It isn't the responsibility of only one standalone component.

2023-08-07 03:41 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +		return decodeURIComponent(params.next ?? '');
Yeah, you see, logic is duplicated.

2023-08-07 04:36 UTC, irinatumanova commented on apps/angular/src/app/features/auth/registration-page/registration-page.component.ts
> +			.subscribe();
If I wrote `first()` above, do I need to unsubscribe via `unsubscribe()`?

2023-08-07 05:27 UTC, dbitkovski approved these changes

2023-08-07 05:38 UTC, merged